### ISSUE TITLE
Bake task regex?

### ISSUE THREAD

**Issue by musdy** [MathiasPaumgarten/grunt-bake#43]
Is there a way to make bake work with a regex and maybe tell it to render into one directory? 

Like this:

```js
bake: {
  build: {
    options: {
      basePath: '<%= yeoman.app %>/views/_includes'
    },
    files: {
      '<%= yeoman.app %>/*': '<%= yeoman.app %>/views/_pages/*',
    }
  }
}
```

Thank you.

**Comment by MathiasPaumgarten** [comment]
Hi there,

The resolving of the file paths is part of `grunt` itself, actually. Which is nice, because it allows a streamlined setup across all different plugins. 

That being said, may I point you to an older closed issue #25. Grunt allows you to pass in an _files-definition-object_ instead of a key value pair. (Note that this object has to be in an array)
With the use of that object you can define more complicated globbing patterns. That seems to solve what you are looking for actually. 

```js
        bake: {
            build: {
                options: {
                    basePath: "<%= yeoman.app %>/views/_includes"
                },
                files: [
                    {
                        expand: true, 
                        cwd: "<%= yeoman.app %>/views/_pages/",   
                        src: [ "**" ],
                        dest: "<%= yeoman.app %>/"
                    }
                ]
            }
        }
```

Let me know if this works for you.
