### ISSUE TITLE
Option to disable transforms

### ISSUE THREAD

**Issue by hudochenkov** [MathiasPaumgarten/grunt-bake#62]
Hi! I have this code in templates:

```html
<p class="greetings">Dear {{var customer_name}},</p>
...
<td class="price">{{var quote.getGrandTotal()|formatPrice}}</td>
```

grunt-bake@0.3.18 and 1.1.1 output:

```html
<p class="greetings">Dear ,</p>
...
<td class="price"></td>
```

But I need this code untouched because it's using in futher tools. I using grunt-bake@0.3.12 and everything fine.

Is there any way to prevent code removing for this case?

**Comment by david-zacharias** [comment]
I am confident that we will find a solution for your issue. One quick hotfix could be to set `options.transformGutter` to a sequence that is definitely not in your code.

Can you please supply what output you expect, hence how did grunt-bake@0.3.12 bake your code.

**Comment by hudochenkov** [comment]
grunt-bake@0.3.12 output:

```html
<p class="greetings">Dear {{var customer_name}},</p>
...
<td class="price">{{var quote.getGrandTotal()|formatPrice}}</td>
```

**Comment by david-zacharias** [comment]
Okay, so you do not want to process the variables at all? Then try setting `process-option` to `false`:

```JS
bake: {
  options: {
    process: false
  }
}
```

**Comment by hudochenkov** [comment]
But at the same time I need to process this `template.html`:

```html
<!--(bake _footer.html campaign="abandon_rev1" unsubscribe="true")-->
```

`_footer.html`:

```html
<!--(bake-start _if="unsubscribe_support")-->
<a href="{{var unsubscribe_url}}?utm_campaign={{campaign}}">Unsubscribe</a>
<!--(bake-end)-->
```

Expected output:

`template.html`

```html
<a href="{{var unsubscribe_url}}?utm_campaign=abandon_rev1">Unsubscribe</a>
```

Will this be processed if I set `process: false`?

**Comment by david-zacharias** [comment]
No it won't, because setting `options.process` to false disables the processing (parsing of template variables) completely. Have you tried the hotfix I suggested? Setting transformGutter to unused sequence like:

```JS
bake: {
  options: {
    transformGutter: '@!@'
  }
}
```

**Comment by hudochenkov** [comment]
Tried on the last version — doesn't work. Input/output as in first message. But with this option grunt doesn't show this error in console:

```
>> Unknown transform: formatPrice
```

**Comment by hudochenkov** [comment]
I think in 0.3.12 if plugin haven't found, for example, `{{var customer_name}}` variable defined it leave the code as is. But in next versions it's just delete code if variable is not found..

**Comment by david-zacharias** [comment]
The problems here are not the transforms. Bake removes unknown placeholder since version 0.3.18. I have added an option `options.removeUndefined` that controls this behavior. You can use the current master (`git install git+https://github.com/MathiasPaumgarten/grunt-bake.git`) for your project till @MathiasPaumgarten checked the changes and bumped a new version. 

@MathiasPaumgarten, make the final decision on the default value for `removeUndefined`. `false` restores the old behavior of grunt-bake, `true` the recent one which I personally prefer, but you are the creator so final decision is up to you :cop:

**Comment by hudochenkov** [comment]
@david-zacharias Thank you! This was very fast :)

**Comment by MathiasPaumgarten** [comment]
Hey guys, just caught up to this. You guys have detected the "issue" that grunt used to leave unrecognized variables as is. We change that behavior int `1.0.0`. Since we had a major bump, I thought it was cool to alter behavior, following [semver rules](http://semver.org/).

For future reference, another hotfix would have been to change the parsing pattern for the variables you want parsed, versus the ones you want left alone with: 

```js
bake: {
    options: {
        parsePattern: /<%\s?([\.\-\w]*)\s?%>/g;
    }
}
```
This would change the grunt parse pattern to something like `<% foo %>` instead of `{{ foo }}`.

However, thanks to @david-zacharias there is an even nicer option place now. I like that it removes variables by default. Because more often than not, if I would forget a variable, and I release it I rather want it to be gone instead of cryptic. But that's up to anyone to decide for themselves. 

Additionally, in order to not change major version, and not break the behavior of  `1.0.0` I leave the default to removing it. 

I'll push the new version now.

**Comment by MathiasPaumgarten** [comment]
I pushed the new version, that @hudochenkov has been using off the master branch to npm under `1.2.0`. That way you can reference to npm instead of Github. (which Github probably prefers :smile:)

:ship:

**Comment by hudochenkov** [comment]
Thank you very much! :)
