### ISSUE TITLE
Unable to process task

### ISSUE THREAD

**Issue by alihaddadkar** [MathiasPaumgarten/grunt-bake#73]
Hi, Thanks for this great plugin.
I want use this plugin but i can't. When run gruntfile.js i get an error.
Please help me.
_____________________________________________

Verifying property bake.build exists in config...ERROR
>> Unable to process task.
Warning: Required config property "bake.build" missing. Use --force to continue.

**Comment by david-zacharias** [comment]
Hi and thank you for using grunt-bake!

The error you described is likely to be caused by a wrong configuration in your `Gruntfile.js`. Please verify that you have loaded grunt-bake `grunt.loadNpmTasks( "grunt-bake" );` and that you have set up the `grunt`-section with task `build`, as written in the [readme](https://github.com/MathiasPaumgarten/grunt-bake/blob/master/README.md):

```JS
grunt.initConfig( {
  bake: {
    build: {
      options: {
        ...
      },
      files: {
        ...
      }
  }
}
```

**Comment by alihaddadkar** [comment]
Thank. My problem was resolved.
