### ISSUE TITLE
Simple bake test

### ISSUE THREAD

**Issue by webnet2** [MathiasPaumgarten/grunt-bake#84]
I tried to run the [Simple Bake ](https://github.com/MathiasPaumgarten/grunt-bake#simple-bake) but it gives me a bunch of syntax error - http://prntscr.com/am8b2i

**Comment by david-zacharias** [comment]
Since the the CI Server runs green [![Build Status](https://travis-ci.org/MathiasPaumgarten/grunt-bake.svg?branch=master)](https://travis-ci.org/MathiasPaumgarten/grunt-bake), I think your error is related to your local configuration / custom code. Without further information about your configuration or how your are runing `Simple Bake` no assistance can be provided. I am closing this issue because it is not a grunt-bake bug.
