### ISSUE TITLE
How to convert a folder with bake ?

### ISSUE THREAD

**Issue by tnqsoft** [MathiasPaumgarten/grunt-bake#94]
Hi !

At the moment, I define file by file in bake config. But I wanna define only folder which container all my HTML. And bake auto scan all files in this folder. Example:
```
bake: {
	build: {
		options: {
			process: function (content, srcpath) {
				return grunt.template.process(content);
			}
		},
		files: {
			"<%= buildDir %>/": "<%= sourceDir %>/pages/*.html"
		}
	}
}
```

How to do that???. Sorry with my English!.

**Comment by david-zacharias** [comment]
Hi, happy to see you are using grunt-bake!

You can use bake for multiple files by making use of [grunts globbing patterns](http://gruntjs.com/configuring-tasks#globbing-patterns). It's the same like for other grunt-plugins.

**Example**
```JS
bake: {
    build: {
        files: [{
            expand: true,
            cwd: 'src',
            src: '*.html',
            dest: 'build/'
        }]
    }
}
```

Since this is no bug or enhancement for bake, I am going to close this issue.

**Comment by tnqsoft** [comment]
Very helpful for me. Thank you very much!.
